name: rent_app
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  http: ^0.13.4
  http_parser: ^4.0.1
  shared_preferences: ^2.0.15
  font_awesome_flutter: ^10.1.0
  shimmer: ^2.0.0
  kartal: ^2.1.0
  image_picker: ^0.8.5+3
  test: ^1.21.1
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  build_runner: ^2.1.11
  path: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/